### ISSUE TITLE
Featured Images

### ISSUE THREAD

**Issue by brandonbryan12** [aisutd/aisutd.github.io#8]
There needs to be a featured images module on the front page

**Comment by brandonbryan12** [comment]
Added carousel and pushed to development. Now, we just need images.
Feel free to provide feedback

**Comment by Michael-Hollister** [comment]
Carousel looks great! Maybe for the last two repeated pictures we could use the attached pictures? Otherwise, this looks ready to merge.

![sep27-3](https://cloud.githubusercontent.com/assets/6564365/19460336/59b32cb8-94a0-11e6-872a-c893b230a05c.jpg)
![sep27-4](https://cloud.githubusercontent.com/assets/6564365/19460337/59b3d514-94a0-11e6-9b70-fb5e71686f59.jpg)

The second one is slightly blurry, but should may look good enough considering the size.

**Comment by brandonbryan12** [comment]
Merged to master and deployed
